### PR TITLE
use sorter from "telescope.sorters"

### PR DESCRIPTION
**Pull request by ghost**
The generic sorter used before would hide the results (I have no idea why). Changing it makes the results appear.

### CODE REVIEW

**Comment by Marskey** [comment]
can you offer me some test data? and your telescope config, i want find why.

**Comment by Marskey** [comment]
I can reproduce this. thank you

**Comment by ghost** [comment]
> can you offer me some test data? and your telescope config, i want find why.

For test data, I was only searching through my nvim config directory.

My telescope config is the following:

```lua
return {
  "nvim-telescope/telescope.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "jvgrootveld/telescope-zoxide",
    { "Marskey/telescope-sg", event = { "VimEnter" } },
    { "barrett-ruth/telescope-http.nvim", event = { "VimEnter" } },
  },
  config = function(_, opts)
    local actions = require "telescope.actions"

    opts.defaults.layout_config.width = 0.99
    opts.defaults.layout_config.height = 0.99

    opts.defaults.layout_config.horizontal = {
      prompt_position = "top",
      preview_width = 0.40,
    }

    opts.defaults.mappings.i["<C-l>"] = actions.send_to_qflist
      + actions.open_qflist
    opts.defaults.mappings.n["<C-l>"] = actions.send_to_qflist
      + actions.open_qflist
    opts.defaults.mappings.i["<C-q>"] = false
    opts.defaults.mappings.n["<C-q>"] = false
    opts.defaults.mappings.i["<esc>"] = actions.close

    opts.defaults.vimgrep_arguments = {
      "rg",
      "--color=never",
      "--no-heading",
      "--with-filename",
      "--line-number",
      "--ignore-case",
      "--column",
      "--smart-case",
      "--trim",
    }

    opts.extensions = {
      ast_grep = {
        command = {
          "ast-grep",
          "--json=stream",
          "-p",
        },
      },
    }

    require("telescope").setup(opts)
    require("telescope").load_extension "harpoon"
    require("telescope").load_extension "ast_grep"
    require("telescope").load_extension "http"
  end,
}
```

**Comment by Marskey** [comment]
Thank you for finding the empty result issue. I was set `generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter` that's why I cant reproduce the problem

**Pull request merged**
